# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mTitle', models.CharField(max_length=32)),
                ('mReleaseDate', models.CharField(max_length=32)),
                ('mDuration', models.CharField(max_length=32)),
                ('mGenre', models.CharField(max_length=32)),
                ('mSynopsis', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
